### ISSUE TITLE
Beta version release checklist

### ISSUE THREAD

**Issue by epicallan** [epicallan/squid#2]
- [x] make `Sql User r` run-able in `SqlPersist m a`
- [x] Use overloaded labels
- [ ] Automatic transactions
- [ ] Maybe consider using a text formatting library
- [ ] Fully support main SQL spec; operators, statements etc
- [x] Basic Migrations
- [ ] Migrations at per with Persistent
- [x] implement table field constraint functionality
- [ ] Misc cleanup
- [ ] Fix column and Field ambiguity
